spring:
  application:
    name: gateway_server
    cloud:
       gateway:
         routes:
           - id: product_service
             uri: lb://product-service
             predicates:
               - Path=/products/**
           - id: cart_service
             uri: lb://cart-service
             predicates:
               - Path=/carts/**
           - id: order_service
             uri: lb://order-service
             predicates:
               - Path=/orders/**
           - id: user_service
             uri: lb://user-service
             predicates:
               - Path=/api/users/**
server:
    port: 8888

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true