datasource:
    url: jdbc:postgresql://localhost:5436/carts
    username: postgres
    password: test12345
    driver-class-name: org.postgresql.Driver
cloud:
    stream:
      bindings:
        testEvent-out-0:
          destination: test-topic # hangi başlığa bu eventi göndereyim?
          content-type: application/json # hangi tür ile göndereyim?
      kafka:
        binder:
          brokers: localhost:9092
jpa:
  hibernate:
    ddl-auto: update